### ISSUE TITLE
How to obtain synthetic foggy cityscape dataset?

### ISSUE THREAD

**Issue by waterbearbee** [kinredon/DA_Detection_Material#3]
Hello,
I have encountered a problem with processing the foggy cityscape datasets and I want to ask you for help. The official website of foggy cityscape only provides transmittance maps. I failed to combine it with the real clear-weather image to obtain the synthetic foggy image. So I would like to ask how to correctly generate the synthetic foggy cityscape dataset.

**Comment by kinredon** [comment]
Actually, you do not need to generate the synthetic foggy cityscape dataset by yourself. You can contact the Cityscapes team for accessing the dataset. Their email: mail@cityscapes-dataset.net. 
The detail see [https://www.cityscapes-dataset.com/](https://www.cityscapes-dataset.com/)
